# Sets led fade effect. Displays firstColor during firstColorDuration time, and then secondColor during secondColorDuration time with a fade between them

LedGroup leds

# RGBA of color, transparency is not available in leds, so alpha will be ignored
std_msgs/ColorRGBA firstColor
std_msgs/ColorRGBA secondColor

#Duration of the transition from one color to the other
duration colorChangeDuration

#Perform a fade when going from secondColor to firstColor
bool reverseFade

#Duration of the effect, when the time is over the previous effect will be restored. 0 will make it display forever
duration effectDuration

#priority of the effect, 0 is no priority, 255 is max priority
uint8 priority

---
#Id of the effect, used to cancel an effect
uint32 effectId

# True if no errors

