# not argument needed to call place recognition 
---
bool success                                               # return true if get successful recognition
float64 confidence                                          # recognition confidence
geometry_msgs/PoseWithCovarianceStamped estimatedPose      # estimated pose (use this only when success == true)



